name: 'task_manager'
version: '0.0.1'
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: '2.0.0-beta.16'
  browser: '^0.10.0'
  dart_to_js_script_rewriter: '^1.0.1'
dev_dependencies:
  test: '^0.12.6'
  angular2_testing: '2.0.0-beta.16'
transformers:
- angular2:
    platform_directives:
    - package:angular2/common.dart#COMMON_DIRECTIVES
    entry_points: web/boot.dart
- dart_to_js_script_rewriter